### ISSUE TITLE
Melhorias classe Employee - Modelo UML

### ISSUE THREAD

**Issue by LGirardelo** [matheusssilva/OculiNuboWeb#11]
**Problema**

Verificando o modelo UML, percebe-se que a classe Employee possui responsabilidades diversificadas. Conforme padrões da orientação a objetos e código limpo, cada classe deve possuir responsabilidades bem específicas. 

**Objetivo**

O objetivo é separar algumas responsabilidades dessa classe.

**Análise técnica**

1º Atributo "Password",  faz referência a acesso ao sistema, desta forma acredito que deveria estar em uma classe chamada "Usuario", juntamente com o login, etc..

2º "Permissions", na classe Employee temos o atributo "Permissions" que é um dicionário, observem que podemos inserir qualquer coisa dentro do dicionário. Acredito que deveríamos criar uma classe responsável pelas permissões dos usuários, por módulo inclusive. Este caso deve ser analisado com calma e pensando como deverá se comportar futuramente, pois além das permissões de acesso as funcionalidades pelos usuários, poderemos ter diversos módulos no sistema, onde uma empresa possa adquirir um ou dois módulos apenas. 

3º "Photo", o atributo "Photo" é um array de bytes, ou seja posso mandar qualquer coisa nesse array, um PDF, arquivo texto, qualquer coisa. Precisamos de uma classe responsável por realizar validações e garantir que o que está sendo criado seja realmente uma "Photo", além de outros controles que poderão surgir, assim centralizamos todas as validações dentro de uma classe só. Ou podemos alterar o atributo para "File", mas mesmo assim teremos que realizar validações.

**Comment by matheusssilva** [comment]
@LGirardelo

1º Cria um exemplo UML com o [Dia](https://wiki.gnome.org/action/show/Apps/Dia?action=show&redirect=Dia) para exemplificar qual seria a tua ideia e anexa em um comentário aqui. Podes pegar o próprio projeto UML e alterar adicionando a tua ideia, só lembra de fazer isso em uma cópia fora do teu repositório local.
Lembrando também que serão coisas distintas, uma coisa é um funcionário operador do retaguarda logar no sistema, outra coisa é a conta da empresa, ou seja a conta da empresa que pagará pelo serviço. Ao visitar o site principal da solução o cliente poderá criar sua conta onde ele informará os dados da empresa, selecionará a forma e dia de pagamento, etc, essa será a conta mestra. Ao criar a conta mestra, uma conta de super operador já é criada automaticamente no sistema, e assim ele pode cadastrar os demais operadores e funcionários que usarão tanto o sistema web quanto os funcionários de rua que usarão o app mobile. Eu ainda não pensei em como os demais operadores irão logar no sistema, é algo que falta planejar.

2º A ideia da propriedade `permissions` é determinar o que cada funcionário poderá ou não fazer no sistema, seja na versão mobile ou no retaguarda web. Por exemplo, um funcionário pode gerenciar cadastros de funcionários (delete, update, create), não pode gerenciar cadastro de clientes, não pode fechar chamados e pode fechar tarefas, assim teríamos o seguinte dicionário: `{'cad_employee': True, 'cad_clients': False, 'closeCalls': False, 'closeTasks': True}`. Esse dicionário não seria preenchido de forma manual pelo funcionário, ele selecionaria checkboxes com essas opções.
A ideia é termos uma solução SaaS (Software como Serviço). O cliente não pagará por módulos e sim por quantidade de acesso, quanto mais operadores de retaguarda, mais caro, quanto mais funcionários de rua ele quiser cadastrar, mas caro ficará. Ou seja, supondo que cobraremos R$50,00 por cada Employee, para uma empresa com um Employee sendo operador do retaguarda e 10 Employees de rua, ela pagaria em torno de 550 reais por mês.
Masse tens uma ideia diferente para o controle das permissões, coloca em UML para que nós possamos analizar.

3º Os models devem ser quase um espelho do que é o banco. Acho que realmente podemos sim validar qual o tipo de arquivo está sendo binarizado, isso seria relativamente simples bastando verificar a extensão, mas acho que mudar o tipo não seria uma boa opção, pois teríamos que ficar fazendo conversões a todo momento e implementando métodos de conversão para binário no model ou na camada de persistência o que não é uma boa prática. Vide como se dá o armazenamento de arquivos no MongoDb [aqui](http://api.mongodb.com/python/current/examples/gridfs.html) e [aqui](https://stackoverflow.com/questions/11915770/saving-picture-to-mongodb).

**Comment by matheusssilva** [comment]
@adesousal, @LGirardelo 
PS. Quando criarem uma Issue que não tenha haver com algo que precise ser desenvolvido, ou seja, que não sja uma tarefa, não anexem ao projeto Backend. Somente devem ser anexadas lá Issue que sejam descrições de algo a ser desenvolvido (tarefa).

**Comment by LGirardelo** [comment]
Olá pessoal, criei o diagrama rapidamente para tentar exemplificar, não sei se fiz corretamente todas as ligações pois ainda não estou totalmente familiarizado com o Dia. 

Deixei o fundo em branco das classes que editei e inclui, para que possam identificar melhor.

A respeito da situação que o @matheusssilva mencionou:

> a conta da empresa, ou seja a conta da empresa que pagará pelo serviço. Ao visitar o site principal da solução o cliente poderá criar sua conta onde ele informará os dados da empresa, selecionará a forma e dia de pagamento, etc, essa será a conta mestra. Ao criar a conta mestra, uma conta de super operador já é criada automaticamente no sistema, e assim ele pode cadastrar os demais operadores e funcionários que usarão tanto o sistema web quanto os funcionários de rua que usarão o app mobile. Eu ainda não pensei em como os demais operadores irão logar no sistema, é algo que falta planejar.

O site da solução conforme mencionado, seria um site que iremos criar separado do sistema, onde empresas poderão entrar em contato conosco e adquirir nosso serviço, correto? uma dúvida, iremos ter uma base de dados para todos os nossos clientes? ou teremos uma instalação separada para cada um deles?

Pois, caso seja apenas uma base para todos, teremos que alterar o diagrama e adicionar uma separação por empresa, e adequar as classes, concordam?



[CloudEyeClasses.dia.zip](https://github.com/matheusssilva/OculiNuboWeb/files/2454289/CloudEyeClasses.dia.zip)

**Comment by matheusssilva** [comment]
Pessoal segue o [vídeo](https://1drv.ms/v/s!AgT_-IcaL0H3hLZv2kiOOmx1vuZJsA) avaliativo que fiz sobre essa questão. Manterei a Issue aberta até que se esgote todos os pontos de vista.

**Comment by LGirardelo** [comment]
Boa noite pessoal

Em relação a modelagem, quero deixar claro que é somente relacionado ao sistema. Não criei nada na modelagem relacionado ao portal.

Reforçando alguns pontos: 

- Criei a classe JobTitle imaginando a seguinte situação: provavelmente iremos precisar gerar relatórios e gráficos mais a diante, desta forma acredito que será necessário filtros por cargo. Se tivermos somente a string na classe Employee, e dois operadores que são do mesmo cargo, mas a string pode estar diferente, (ex: um cadastrado com letra minuscula e outro cadastrado com letra maiúscula, etc..) isso será um problema ao realizar filtros, digo isso pois já tive esses problemas. 

- Fiz a herança entre Client e Person, pois imagino que adiante o cliente poderá abrir chamado diretamente pelo sistema, além de acompanhar os chamados que foram abertos e futuramente poderá gerar relatórios etc, algo nesse sentido. Acredito ser uma funcionalidade que agregaria. Mas só se acharem que vale a pena, senão não é algo necessário de momento. Mas a modelagem permitiria essa situação, como pode-se observar, uma Person não precisa necessariamente ter um usuário vinculado.

- Profile: no modelo anterior não havia essa classe, imaginem o seguinte cenário: o sistema possui 30 funcionalidades, ao cadastrar usuários o administrador terá que configurar as 30 permissões de acesso para cada um. Com a classe Profile essa configuração será feita somente para o Profile e ao cadastrar o User ele será vinculado a um Profile já configurado. 

- Enum Permission: acredito que podemos deixar da forma que você falou no vídeo @matheusssilva

**Comment by LGirardelo** [comment]
@matheusssilva surgiu mais uma dúvida:

- O atributo car da classe Employee ilustra o carro que o empregado está usando no momento, correto? não será necessário guardar histórico dos carros que o empregado utilizou? 
Por exemplo, um empregado vai utilizar um carro (que faz uma média X e da Y gasto para a empresa) em um determinado período. Caso troque de carro, da forma que está a modelagem não teremos o  histórico.
Acredito ser uma informação interessante para a empresa, o que acha?

**Comment by matheusssilva** [comment]
@LGirardelo

Sobre o ponto 1, é possível fazer reaproveitamento de dados mesmo que esses dados não estejam em um Document separado. Lembra que vamos usar mongodb que é NOSQL, um conceito diferente, porém isso também é possível com bancos relacionais. O raciocínio é basicamente buscar no Document de Employees as funções já cadastrada. Pode-se criar tratamentos no controller para evitar a confusão de maiúsculas e minusculas.

Sobre o ponto 2, tua ideia é valida, mas pode ficar mais pra frente, pois ainda teremos que definir que de que forma será feita o login no sistema. Após definirmos isso podemos voltar a analisar essa parte. Boa parte das sugestões que deu eu aderi, fazer essa adaptação seria mais tranquilo agora no futuro pois seria basicamente acrescentar mais propriedades. Porém o que podemos fazer nesse caso é fornecer um meio de integração, um web service talvez para que o nosso cliente integre a solução com o site pessoal dele, e no site dele ele forneceria um meio para que o cliente dele abrisse chamados e através dessa integração o nosso sistema receberia e criaria um novo chamado.
Deve-se ainda destacar que nem sempre um chamado do cliente se converte em um chamado no sistema, para muitos segmentos os chamados se resolvem via telefone. Porém isso é algo que será discutido novamente em um futuro próximo.

Pontos 3 e 4 foram deferidos e incorporados ao projeto.

Sobre o ultimo comentário, é válido, irei analisar.

**Comment by matheusssilva** [comment]
Também implementei a tua sugestão sobre a classe Car. Basicamente criei uma classe de uso dos carros.
