### ISSUE TITLE
Analise e ajustes de classes Car, Telephone, Address, Employee e EmployeeGroup

### ISSUE THREAD

**Issue by matheusssilva** [matheusssilva/OculiNuboWeb#4]
Baseado no novo projeto UML, analisar e caso necessário modificar as seguintes classes:

- [x] Car.
- [x] Telephone.
- [x] Address.
- [x] Employee.
- [x] EmployeeGroup.

**Comment by matheusssilva** [comment]
@LGirardelo passei a Issue pra ti. Ademir passará a ficar com Issues de menor urgência.

**Comment by LGirardelo** [comment]
@matheusssilva Realizei os ajustes das classes, porém ficou pendente a classe Employee, gostaria de validar a Issue #11 antes de implementar essa classe.
